In [1]:
import tensorflow as tf
tf.compat.v1.enable_eager_execution()

import numpy as np

With eager execution, we don't need to create a session

In [3]:
x = tf.constant(11)
y = tf.constant(11)
z = x*y
print(z)

tf.Tensor(121, shape=(), dtype=int32)


To get the output value

In [4]:
z.numpy()

np.int32(121)

Math operations in TensorFlow

In [5]:
x = tf.constant([1., 2., 3.])
y = tf.constant([3., 2., 1.])

tf.add to add two numbers

In [6]:
sum = tf.add(x,y)
sum.numpy()

array([4., 4., 4.], dtype=float32)

tf.subtract function is used for finding the difference between two numbers:

In [7]:
difference = tf.subtract(x,y)
difference.numpy()

array([-2.,  0.,  2.], dtype=float32)

tf.multiply function is used for multiplying two numbers

In [8]:
product = tf.multiply(x,y)
product.numpy()

array([3., 4., 3.], dtype=float32)

Divide two numbers using tf.divide

In [9]:
division = tf.divide(x,y)
division.numpy()

array([0.33333334, 1.        , 3.        ], dtype=float32)

Dot product can be computed as follows

In [10]:
dot_product = tf.reduce_sum(tf.multiply(x, y))
dot_product.numpy()

np.float32(10.0)

find the index of the minimum and maximum elements

In [11]:
x = tf.constant([10, 0, 13, 9])
print(tf.argmin(x).numpy())
print(tf.argmax(x).numpy())

1
2


Squared difference between x and y

In [12]:
x = tf.Variable([1,3,5,7,11])
y = tf.Variable([1])
tf.math.squared_difference(x,y).numpy()

array([  0,   4,  16,  36, 100], dtype=int32)

Typecassting: From one data type to another

In [13]:
print(x.dtype)

<dtype: 'int32'>


In [14]:
x = tf.cast(x, dtype=tf.float32)
print(x.dtype)

<dtype: 'float32'>


Concatenate the two matrices:

In [15]:
x = [[3,6,9], [7,7,7]]
y = [[4,5,6], [5,5,5]]

Concatenate the matrices row-wise

In [16]:
tf.concat([x, y], 0).numpy()

array([[3, 6, 9],
       [7, 7, 7],
       [4, 5, 6],
       [5, 5, 5]], dtype=int32)

Concatenate the matrices column-wise

In [17]:
tf.concat([x, y], 1).numpy()

array([[3, 6, 9, 4, 5, 6],
       [7, 7, 7, 5, 5, 5]], dtype=int32)

Stack the x matrix using the stack function

In [18]:
x = tf.Variable([[1.0, 5.0], [2.0, 3.0]])
x.numpy()

array([[1., 5.],
       [2., 3.]], dtype=float32)

The reduce_mean operation

In [19]:
x = tf.Variable([[1.0, 5.0], [2.0, 3.0]])
x.numpy()

array([[1., 5.],
       [2., 3.]], dtype=float32)

Compute the mean value of x

In [20]:
tf.reduce_mean(input_tensor=x).numpy()

np.float32(2.75)

Compute the mean across the row

In [21]:
tf.reduce_mean(input_tensor=x, axis=0).numpy()

array([1.5, 4. ], dtype=float32)

Compute the mean across the column

In [22]:
tf.reduce_mean(input_tensor=x, axis=1, keepdims=True).numpy()

array([[3. ],
       [2.5]], dtype=float32)

Draw random values from the probability distributions:

In [23]:
tf.random.normal(shape=(3,2), mean=10.0, stddev=2.0).numpy()
tf.random.uniform(shape = (3,2), minval=0, maxval=None, dtype=tf.float32,).numpy()

array([[0.5913557 , 0.7050874 ],
       [0.56414545, 0.0860467 ],
       [0.5919244 , 0.52158654]], dtype=float32)

Compute the softmax probabilities:

In [24]:
x = tf.constant([7., 2., 5.])
tf.nn.softmax(x).numpy()

array([0.8756006 , 0.00589975, 0.11849965], dtype=float32)

Computing gradients

Define the square function

In [25]:
def square(x):
  return tf.multiply(x, x)

Square function using tf.GradientTape

In [27]:
with tf.GradientTape(persistent=True) as tape:
  print(square(6.).numpy())

36.0


**TensorFlow 2.0 and Keras**

Defining a sequential model

In [28]:
from tensorflow import keras

In [29]:
from keras.models import Sequential
from keras.layers import Dense

In [30]:
model = Sequential()

Adding layers to our model

In [31]:
model.add(Dense(13, input_dim=7, activation='relu'))
model.add(Dense(7, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Defining a functional model

In [32]:
input = tf.keras.Input(shape=(2,))
layer1 = Dense(10, activation='relu')(input)
layer2 = Dense(10, activation='relu')(layer1)
output = Dense(1, activation='sigmoid')(layer2)
model = tf.keras.Model(inputs=input, outputs=output)

Compiling the model

In [33]:
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

Training the model

MNIST digit classification using
TensorFlow 2.0


In [34]:
mnist = tf.keras.datasets.mnist

Splitting the dataset into train and test

In [35]:
(x_train,y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [36]:
x_train, x_test = tf.cast(x_train/255.0, tf.float32), tf.cast(x_test/255.0, tf.float32)
y_train, y_test = tf.cast(y_train,tf.int64),tf.cast(y_test,tf.int64)

Model creation

In [37]:
model = tf.keras.models.Sequential()

Adding layers to our model

In [38]:
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(256, activation="relu"))
model.add(tf.keras.layers.Dense(128, activation="relu"))
model.add(tf.keras.layers.Dense(10, activation="softmax"))

Model compilation

In [39]:
model.compile(optimizer='sgd', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

Model trraining

In [40]:
model.fit(x_train, y_train, batch_size=32, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.7218 - loss: 1.0162
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9167 - loss: 0.2930
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9336 - loss: 0.2331
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.9433 - loss: 0.1969
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9521 - loss: 0.1701
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - accuracy: 0.9566 - loss: 0.1510
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.9618 - loss: 0.1342
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9645 - loss: 0.1201
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9686 - loss: 0.1105
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9727 - loss: 0.0993


Model evaluation

In [41]:
model.evaluate(x_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9604 - loss: 0.1276


[0.10943730175495148, 0.9661999940872192]